name: React CI Pipeline

on:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Welcome Message
        run: echo "Hello Arjita! My first GitHub Action is running."